language: python
python:
  - "2.7"
env:
  - without_spykeutils=''
  - without_spykeutils=true
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy
before_script:
  - "pip install spykeutils"
script:
  - "python pymuvr/test/test_pymuvr.py"
