language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - with_spykeutils=true
  - with_spykeutils=false
install:
  - "pip install -q numpy"
  - "pip install ." 
script:
  - "travis_wait 45 tests/travis_script.sh"
